apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kube-prom-stack
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: cluster1
        url: https://kubernetes.default.svc

  template:
    metadata:
      name: 'stack-{{cluster}}'
      labels:
        app: prometheus
        scope: argocd-monitoriing
    spec:
      project: default
      source:
        repoURL: https://github.com/mhammadsaani/kube-prom-stack-2
        targetRevision: HEAD
        path: kube-prometheus-stack/
        helm:
          valueFiles:
            - "values-common.yaml"
            - "values-{{cluster}}.yaml"
      destination:
        server: '{{url}}'
        namespace: argocd-monitoriing
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
